<?php
$title = 'Login';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;

$form->setAttribute('action', $this->url('blog', array('action' => 'login')));
$form->prepare();

echo $this->form()->openTag($form);

?>

<div class="form-group">
    <?php echo $this->formRow($form->get('username')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('password')); ?>
</div>

<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>
