<?php

$tags = [];
/** @var $tag \Blog\Entity\Tag */
foreach ($this->entry->getTags() as $tag) {
    array_push($tags,$tag->getName());
}
?>

<h1 class="mt-4">
    <?php echo $this->escapeHtml($this->entry->getTitle());?>
</h1>
<p class="lead"> by
    <a href="<?= $this->url('home/userEntries', ['user' =>  $this->entry->getAuthor()->getUsername()])?>">
        <?php echo $this->escapeHtml($this->entry->getAuthor()->getUsername());?>
    </a>
    Tags: <?php echo $this->escapeHtml(implode(',' , $tags));?>
</p>
<hr>
<p>
    Posted on <?php echo $this->escapeHtml(date('d.m.Y',strtotime($this->entry->getDate()))) ?>
</p>
<hr>
<p>
    <?php echo $this->escapeHtml($this->entry->getContent());?>
</p>
<hr>
