<nav class="text-center" aria-label="Page navigation">
    <ul class="pagination">
        <?php if (! isset($this->pages->previous)): ?>
            <li class="disabled"><a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
        <?php else: ?>
            <li><a href="<?php echo $this->url('home', ['page' =>  $this->pages->previous]);?>" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
        <?php endif; ?>

        <?php foreach ($this->pages->pagesInRange as $num): ?>
            <?php if ($num === $this->pages->current): ?>
                <li class="active"><a href="<?php echo $this->url('home', ['page' =>  $num])?>"><?php echo $num ?> <span class="sr-only">(current)</span></a></li>
            <?php else: ?>
                <li><a href="<?php echo $this->url('home', ['page' =>  $num])?>"><?php echo $num ?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>

        <?php if (! isset($this->pages->next)): ?>
            <li class="disabled"><a href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
        <?php else: ?>
            <li><a href="<?php echo $this->url('home', ['page' =>  $this->pages->next ]);?>" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
        <?php endif; ?>
    </ul>
</nav>