<?php echo $this->partial('blog/partial/entry.phtml', ['entry' => $this->entry])?>

<div class="card my-4">
    <h4 class="card-header">Leave a Comment:</h4>
    <div class="card-body">
        <?php $this->form->prepare(); ?>
        <?php echo $this->form()->openTag($this->form); ?>
        <div class="form-group">
            <?php echo $this->formRow($this->form->get('nameInput')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($this->form->get('commentMail')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($this->form->get('commentUrl')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($this->form->get('contentComment')); ?>
        </div>
            <?php echo $this->formSubmit($this->form->get('addComment'));; ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
<?php foreach ($this->comments as $comment) : ?>
<div class="media mb-4">
    <div class="media-body">
        <h5 class="mt-0"><?php echo $this->escapeHtml($comment->getUser()).' meint: ('. date('d.m.Y H:i:s',strtotime($comment->getDate())). ')'; ?></h5>
        <?php echo $this->escapeHtml($comment->getComment()) ?>
    </div>
</div>
<?php endforeach; ?>










