<?php


$title = 'Edit Entry';
$this->headTitle($title);
?>
<h1 class="text-center"><?php echo $this->escapeHtml($title); ?></h1>
<?php

$this->form->prepare();
$this->form->setAttribute('action', $this->url('editEntry', ['id' => $this->id]));
echo $this->form()->openTag($this->form);

?>

<?php echo $this->bootstrapHelper()->formGroupDiv($this->formRow($this->form->get('title'))) ?>

<?php echo $this->bootstrapHelper()->formGroupDiv($this->formRow($this->form->get('content'))) ?>

<?php echo $this->formSubmit($this->form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>
